import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(__dirname, '../package.json'), 'utf8'));
const out = `// Auto-generated by scripts/gen-version.mjs — do not edit by hand.\nexport const VERSION = '${pkg.version}';\n`;
writeFileSync(join(__dirname, '../src/version.ts'), out);
console.log('gen-version: wrote src/version.ts with VERSION =', pkg.version);
